# -*- coding: utf-8 -*-
"""internship.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEzD2-VjGTLjNK-owHOjWkTvqt96-oQV
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import missingno
# %matplotlib inline
import seaborn as sns

solution=pd.read_csv('SampleSuperstore.csv')

solution.head()

solution.tail()

solution.describe()

solution.isnull().sum()

missingno.matrix(solution,figsize=(30,10))

solution.dtypes

fig = plt.figure(figsize=(20,10))
sns.countplot(y='Ship Mode', data=solution);

fig = plt.figure(figsize=(20,40))
sns.countplot(y='State', data=solution);

fig = plt.figure(figsize=(20,10))
sns.countplot(y='Region', data=solution);

fig = plt.figure(figsize=(20,10))
sns.countplot(y='Category', data=solution);

fig = plt.figure(figsize=(20,15))
sns.countplot(y='Sub-Category', data=solution);

plt.figure(figsize=(16,10))
plt.bar(solution['State'],solution["Profit"])
plt.xlabel("State",fontsize=20)
plt.ylabel("Profit",fontsize=20)
plt.title("State Profit")
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(16,10))
plt.bar(solution['State'],solution["Sales"])
plt.xlabel("State",fontsize=20)
plt.ylabel("Sales",fontsize=20)
plt.title("State Sales")
plt.xticks(rotation=90)
plt.show()

A=(solution["Ship Mode"].value_counts())/len(solution["Ship Mode"])*100
A.plot(kind='bar',color='b')
plt.show()

A=(solution["Region"].value_counts())/len(solution["Region"])*100
A.plot(kind='bar',color='b')
plt.show()

A=(solution["Category"].value_counts())/len(solution["Category"])*100
A.plot(kind='bar',color='b')
plt.show()

A=(solution["Sub-Category"].value_counts())/len(solution["Sub-Category"])*100
A.plot(kind='bar',color='b')
plt.show()

solution.pivot_table(index="Segment",values="Sales",columns="Discount",aggfunc='median')

solution.pivot_table(index="Segment",values="Profit",columns="Discount",aggfunc='median')

